rule_1:
  alertingEnabled: true
  archived: false
  archivedTime: null
  liveRuleEnabled: true
  ruleId: ru_06e0ae39-f89d-4173-8b1e-21fb3fa8fd13
  ruleType: MULTI_EVENT
  versionCreateTime: '2023-12-05T18:52:21.667567Z'
  versionId: ru_06e0ae39-f89d-4173-8b1e-21fb3fa8fd13@v_1701802341_667567000
rule_2:
  alertingEnabled: false
  archived: false
  archivedTime: null
  liveRuleEnabled: false
  ruleId: ru_e960310d-6f6f-4bcd-9e7e-e68a0e2ba3bf
  ruleType: MULTI_EVENT
  versionCreateTime: '2023-11-17T22:41:01.293167Z'
  versionId: ru_e960310d-6f6f-4bcd-9e7e-e68a0e2ba3bf@v_1700260861_293167000
okta_new_api_token_created:
  alertingEnabled: false
  archived: false
  archivedTime: null
  liveRuleEnabled: false
  ruleId: ru_a2d1705b-6c24-49dc-ad11-86ec86696fa4
  ruleType: SINGLE_EVENT
  versionCreateTime: '2023-11-17T22:41:01.293167Z'
  versionId: ru_a2d1705b-6c24-49dc-ad11-86ec86696fa4@v_1700260861_293167000
okta_suspicious_use_of_a_session_cookie:
  alertingEnabled: false
  archived: false
  archivedTime: null
  liveRuleEnabled: false
  ruleId: ru_bcf153b7-ffd3-47c5-981f-53630e3ff7df
  ruleType: MULTI_EVENT
  versionCreateTime: '2023-11-17T22:41:01.293167Z'
  versionId: ru_bcf153b7-ffd3-47c5-981f-53630e3ff7df@v_1700260861_293167000
